deploy:
  provider: pages 
  skip-cleanup: true
  github_token: $GITHUB_TOKEN 
  keep_history: true
  local-dir: public 
    

before_install: 
  - "git config --global user.name \"Bin Yu\""
  - "git config --global user.email \"yubin.on.ca@gmail.com\""
  - "sed -i \"s#{GITHUB_REPO}#${GITHUB_TOKEN}@${GITHUB_REPO}#g\"  _config.yml"

  # 修改站点配置文件LeanCloud Counter Security里的LeanCloud Counter App ID的信息
  - sed -i "s#${LEANCLOUD_VISITORCOUNTER_TMP_ID}#${LEANCLOUD_VISITORCOUNTER_ID}#g" _config.yml
  # 修改主题配置配置文件里LeanCloud Counter的App ID的信息
  - sed -i "s#${LEANCLOUD_VISITORCOUNTER_TMP_ID}#${LEANCLOUD_VISITORCOUNTER_ID}#g" themes/next/_config.yml

  - "git ls-files -z | while read -d '' path; do touch -d \"$(git log -1 --format=\"@%ct\" \"$path\")\" \"$path\"; done"
  - "git clone --branch=master --single-branch https://${GITHUB_REPO}.git .deploy_git"

before_script: 
  - "hexo clean"
git: 
  depth: false

branches: 
  only: 
    - pg-source
env: 
  global: 
    #GITHUB_REPO: github.com/BinYuOnCa/binyuonca.github.com
    #GITHUB_TOKEN: 07ee99afebd067c6b418141e7dd7737791f54a83
    #LEANCLOUD_VISITORCOUNTER_TMP_ID: ejiGxeycbXDtKDB0eLd0TOvx-MdYXbMMI
    #LEANCLOUD_VISITORCOUNTER_ID: ejiGxeycbXDtKDB0eLd0TOvx-MdYXbMMI
    secure: "Oh7JAm/I9+JL+hVSfBIXBxB8LhaHxTfFWxtUgfyXAZLMTAxleUoBNBKd5d3FVX34c6j/JGdlITZEbc1p9sfM2j+aQoIdMZ2M7F56Vf22q25XCVG2niwtEvoWKMLgo+bcbxuW/FEXcDhuIZ7k4dJh5dzbTB5uRdgWFNJtd2IV57nLv/EwUvm7JVXgkc0eiRn5DyXJT0yBVWsQeHDsUrlIGRAZmTFauwr0wpnyOAaBbTHvwGebkOQNDl+e0AzvLWFuxjopuUk1iXSa2ItDAKyKTT5VjkwXMOX3NkwBfchHqK1jwLUqiB5ixJzVRPqLxGOnQRZR87GS7ziYrtGvQCn5JRKtAm48hKGe/NL3OxfBb0uc0K9BanjAkbVcPFuNCUd3ulJ3J7XQdKteq5vX+AjrWxU+Cb1EpFf9rDIAEzNoTx3mipFqA0b7Vu8U9Q2JhrqhIh7NHu7Zy7I8/dNWfO51wC8yNTkE/Pdk8NykuVZnP2A77zf+T4SQAwwhJCUcQ7tLUgFRt49QQ9OuCV0NojJwMN7AUJIkXM3+JHhP8lxm3ps2jjJQF30IQXaq7h6YDqJ+xE/wOwlkktyO3Ayt+ic7NrGXDsGLlatNz6fMeuB+9sHdYlv1C2B6FIEdubIoJboE/N8KvcM0nCMKd/Bcb5+nAGh+Are8oVaM/Q/8f2xocIE="
    #secure: "UlC7SpONPH5cLoUhyKfRO7BHma2Wic3jgkVEZk4dKfAMclPm3qG1NT2pRvTdGboD+n9UtMW8U3am4JG0lpt8tG1SBl4R1rUVj2ayGxkX9r9VJAZvIKQNb/SIkdXT2ykZgE9bvgrGxhvLQc04GxbR184hoe53AiSoi/J3Gx7wA82+4UVDJDrIzAB3LOFPNUUizLjjnyyvkQX981zb8C7X5fjH3+XhiDoJiDEjN14HCpwDZn0pyy7Vbcqs7z6+pA/UaFqTPlmGRNeiy1X6vS5i3fjwR+ucrQLgzuBgjRD/o+7x5WIPhhbnQB86myJRmpqMDxu1Ap9LJejtKbUQ6F0eeMBDTh71l8ueCRvJNNAxJbjZMjP1CWZ9vYXde4VRwEPys6TANy5xbxj4V4VYuI0lolqdbkosmquQ2+j779IjR5wzAvXOHeX7n7TtFWl5bqk/VnaLIN65RNm6XLV6Lwqf88N+0Zs2HdX7sv9mZUxLDqt3LeyJc7emiTRiE5LEmrJjk+uOizkAHphUc0fwSHKSDeeq5f1uby9qXPD8MtIhKrguvcOmOngl6SJ8ruFT9Y+qFdiyZC5At/mz6AYox3+pxEFZD5MYLMX2n8pHtMnCS6Rc+V6B5KqHN5D3yvA4TdjNaeCC2DmxvF++xEqZDdptjB0fS4U8jBrPCYUqQeBpBBY="
    

install: 
  - npm install babel-runtime@6
  - npm install -g hexo-cli
  - npm install hexo --save
  - npm install hexo-deployer-git --save
  - npm install hexo-leancloud-counter-security --save
  - npm install
language: node_js
node_js: stable
script: 
  - "hexo g"
#  - "hexo d"
