# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: From Backend Engineer to Data Scientist
subtitle: ''
description: ''
keywords:
author: Bin Yu  
language: en
timezone: 'America/Toronto'

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://binyuonca.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: True  # Chged to True to enable loading local image, Bin Yu 20200707
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
leancloud_counter_security:
  enable_sync: true

  app_id: PFfDnND4aRCqfyvyNs3I5zeB-MdYXbMMI
  #${LEANCLOUD_VISITORS_ID}
  app_key: SmRgM6YQLDJp6vPh8lddYsDQ
  #${LEANCLOUD_VISITORS_KEY}


  username: ben-hexo-counter
  password: sZtq7SgMnmkymf3RCqfyvyNs3I


  #username: ${LEANCLOUD_USER_ID}
  #password: ${LEANCLOUD_COUNTER_PWD}

  #server_url: https://leancloud.cn

  #app_id: ejiGxeycbXDtKDB0eLd0TOvx-MdYXbMMI
  #app_key: lNbbwMxW4v0L1xbOm5fMH2SM
  #username: ben-hexo-lc 
  #password: $LEANCLOUD_COUNTER_PWD
  # bXDtKDB0eLNbbwMxW4v


## Themes: https://hexo.io/themes/
theme: next 

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
-
  type: git
  repo: https://github.com/BinYuOnCa/binyuonca.github.com.git
  #repo: git@github.com:BinYuOnCa/binyuonca.github.com.git
  branch: master
  name: BinYuOnCa
  email: yubin.on.ca@gmail.com
  token: ${GITHUB_TOKEN}
  #d12fa76eaeb882bf51fcde4fcc2725002526835b
  #07ee99afebd067c6b418141e7dd7737791f54a83
  #${GITHUB_TOKEN}
  message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"
-  
  type: leancloud_counter_security_sync
        
